# Generated by Django 5.2.17 on 2026-09-09 01:26

import core.models.functions
import core.models.organization
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models

# `unaccent(text)` from the extension is only STABLE, because it looks the
# dictionary up through search_path, and PostgreSQL will not index a
# non-IMMUTABLE expression. Naming the dictionary explicitly removes that
# dependency, which makes the wrapper safe to declare IMMUTABLE. It is needed
# before any table exists: `tag`'s unique index is built on top of it.
CREATE_IMMUTABLE_UNACCENT = """
    CREATE OR REPLACE FUNCTION immutable_unaccent(text) RETURNS text
        LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
    AS $func$
        SELECT public.unaccent('public.unaccent'::regdictionary, $1)
    $func$;
"""

DROP_IMMUTABLE_UNACCENT = "DROP FUNCTION IF EXISTS immutable_unaccent(text);"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.RunSQL(
            sql=CREATE_IMMUTABLE_UNACCENT, reverse_sql=DROP_IMMUTABLE_UNACCENT
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('VIEWER', 'Viewer'), ('AUDITOR', 'Auditor'), ('ADMIN', 'Administrator')], default='VIEWER', max_length=20)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'db_table': 'app_user',
                'ordering': ['name'],
            },
            managers=[
                ('objects', core.models.organization.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'discipline',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'document_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_area', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'area',
                'ordering': ['acronym'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.area'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login')], max_length=10)),
                ('entity', models.CharField(max_length=40)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('record', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('confidentiality_level', models.CharField(choices=[('PUBLIC', 'Public'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], default='CONFIDENTIAL', max_length=12)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.discipline')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('justification', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_accesses', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'document accesses',
                'db_table': 'document_access',
            },
        ),
        migrations.CreateModel(
            name='DocumentArea',
            fields=[
                ('pk', models.CompositePrimaryKey('document_id', 'area_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_areas', to='core.area')),
                ('document', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='document_areas', to='core.document')),
            ],
            options={
                'db_table': 'document_area',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='areas',
            field=models.ManyToManyField(related_name='documents', through='core.DocumentArea', to='core.area'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.project'),
        ),
        migrations.CreateModel(
            name='ProjectDiscipline',
            fields=[
                ('pk', models.CompositePrimaryKey('project_id', 'discipline_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_disciplines', to='core.discipline')),
                ('project', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_disciplines', to='core.project')),
            ],
            options={
                'db_table': 'project_discipline',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='disciplines',
            field=models.ManyToManyField(related_name='projects', through='core.ProjectDiscipline', to='core.discipline'),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OBSOLETE', 'Obsolete')], default='PENDING', max_length=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('change_description', models.CharField(blank=True, max_length=255, null=True)),
                ('auditor_comment', models.TextField(blank=True, null=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audited_revisions', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_revisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.document')),
            ],
            options={
                'db_table': 'revision',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('extension', models.CharField(choices=[('pdf', 'PDF'), ('dwg', 'AutoCAD drawing'), ('dxf', 'Drawing exchange format'), ('doc', 'Word document (legacy)'), ('docx', 'Word document'), ('xls', 'Excel spreadsheet (legacy)'), ('xlsx', 'Excel spreadsheet')], max_length=5)),
                ('mime_type', models.CharField(max_length=127)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('uploaded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('revision', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.revision')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(core.models.functions.ImmutableUnaccent('name')), name='uq_tag_name_norm'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='ck_tag_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('pk', models.CompositePrimaryKey('document_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='core.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='core.tag')),
            ],
            options={
                'db_table': 'document_tag',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(related_name='documents', through='core.DocumentTag', to='core.tag'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__contains', '@'), models.Q(('email__startswith', '@'), _negated=True)), name='ck_app_user_email_has_at'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='ck_app_user_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['AUTHOR', 'VIEWER', 'AUDITOR', 'ADMIN'])), name='ck_app_user_role'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity', 'entity_id', '-occurred_at'], name='ix_audit_entity'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-occurred_at'], name='ix_audit_user'),
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN'])), name='ck_audit_log_action'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['document'], name='ix_document_access_pending'),
        ),
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='uq_document_access'),
        ),
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='ck_document_access_status'),
        ),
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PENDING'), ('approver__isnull', True)), models.Q(models.Q(('status', 'PENDING'), _negated=True), ('approver__isnull', False), ('decided_at__isnull', False)), _connector='OR'), name='ck_document_access_decision'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['-issue_date'], name='ix_revision_issue_date'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['created_at'], name='ix_revision_pending'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uq_revision_document_version'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='ck_revision_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'OBSOLETE'])), name='ck_revision_status'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PENDING'), models.Q(('auditor__isnull', False), ('audited_at__isnull', False)), _connector='OR'), name='ck_revision_decision_has_auditor'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('document',), name='uq_revision_current'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['sha256'], name='ix_file_sha256'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(condition=models.Q(('extension__in', ['pdf', 'dwg', 'dxf', 'doc', 'docx', 'xls', 'xlsx'])), name='ck_file_extension'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0), ('size_bytes__lte', 104857600)), name='ck_file_size_bytes'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='ck_file_sha256_hex'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('revision', 'sha256'), name='uq_file_revision_sha256'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='ix_document_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'discipline', 'document_type', 'confidentiality_level'], name='ix_document_filters'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='ck_document_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('confidentiality_level__in', ['PUBLIC', 'CONFIDENTIAL', 'SECRET'])), name='ck_document_confidentiality_level'),
        ),
    ]
