# Generated by Django 5.2.17 on 2026-09-22 00:19

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fill_and_require_text_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='ix_document_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-updated_at', '-id'], name='ix_document_recent'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='ix_document_created_at'),
        ),
    ]
