# Generated by Django 5.2.17 on 2026-10-08 01:23

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_deletion_requested_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'db_table': 'legal_document',
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('change_notes', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_legal_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.legaldocument')),
            ],
            options={
                'db_table': 'legal_document_version',
            },
        ),
        migrations.CreateModel(
            name='LegalClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60)),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='clauses', to='core.legaldocumentversion')),
            ],
            options={
                'db_table': 'legal_clause',
            },
        ),
        migrations.CreateModel(
            name='UserLegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='core.legaldocumentversion')),
            ],
            options={
                'db_table': 'user_legal_acceptance',
            },
        ),
        migrations.CreateModel(
            name='UserClauseConsent',
            fields=[
                ('pk', models.CompositePrimaryKey('acceptance_id', 'clause_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('accepted', models.BooleanField()),
                ('decided_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clause_consents', to='core.legalclause')),
                ('acceptance', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='clause_consents', to='core.userlegalacceptance')),
            ],
            options={
                'db_table': 'user_clause_consent',
            },
        ),
        migrations.AddIndex(
            model_name='legaldocumentversion',
            index=models.Index(condition=models.Q(('status', 'PUBLISHED')), fields=['document', '-version'], name='ix_legal_version_published'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uq_legal_version'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'RETIRED'])), name='ck_legal_version_status'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('published_at__isnull', False), _connector='OR'), name='ck_legal_version_published_at'),
        ),
        migrations.AddConstraint(
            model_name='legalclause',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='uq_legal_clause_code'),
        ),
        migrations.AddConstraint(
            model_name='legalclause',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='uq_legal_clause_position'),
        ),
        migrations.AddConstraint(
            model_name='legalclause',
            constraint=models.CheckConstraint(condition=models.Q(('body__regex', '\\S')), name='ck_legal_clause_body_not_blank'),
        ),
        migrations.AddIndex(
            model_name='userlegalacceptance',
            index=models.Index(fields=['version'], name='ix_legal_acceptance_version'),
        ),
        migrations.AddConstraint(
            model_name='userlegalacceptance',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='uq_user_legal_acceptance'),
        ),
        migrations.AddConstraint(
            model_name='userlegalacceptance',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('accepted_at')), _connector='OR'), name='ck_user_legal_acceptance_revoked'),
        ),
    ]
